// <auto-generated />
namespace Emulsion.Database.Migrations

open System
open Emulsion.Database
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<EmulsionDbContext>)>]
[<Migration("20220828121717_FileNameAndMimeType")>]
type FileNameAndMimeType() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.AddColumn<string>(
            name = "FileName"
            ,table = "TelegramContents"
            ,``type`` = "TEXT"
            ,nullable = true
            ) |> ignore

        migrationBuilder.AddColumn<string>(
            name = "MimeType"
            ,table = "TelegramContents"
            ,``type`` = "TEXT"
            ,nullable = true
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropColumn(
            name = "FileName"
            ,table = "TelegramContents"
            ) |> ignore

        migrationBuilder.DropColumn(
            name = "MimeType"
            ,table = "TelegramContents"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.10")
            |> ignore

        modelBuilder.Entity("Emulsion.Database.Entities.TelegramContent", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("ChatUserName")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("FileId")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string option>("FileName")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<Int64>("MessageId")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string option>("MimeType")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("TelegramContents") |> ignore

        )) |> ignore

