// SPDX-FileCopyrightText: 2024 Emulsion contributors <https://github.com/codingteam/emulsion>
//
// SPDX-License-Identifier: MIT

// <auto-generated />
namespace Emulsion.Database.Migrations

open System
open Emulsion.Database
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Migrations

[<DbContext(typeof<EmulsionDbContext>)>]
[<Migration("20230625203424_ArchiveEntry")>]
type ArchiveEntry() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "ArchiveEntries"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Int64>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    ).Annotation("Sqlite:Autoincrement", true)
                MessageSystemId =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                DateTime =
                    table.Column<DateTimeOffset>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Sender =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
                Text =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_ArchiveEntries", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "ArchiveEntries"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.10")
            |> ignore

        modelBuilder.Entity("Emulsion.Database.Entities.ArchiveEntry", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<DateTimeOffset>("DateTime")
                .IsRequired(true)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("MessageSystemId")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Sender")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Text")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("ArchiveEntries") |> ignore

        )) |> ignore

        modelBuilder.Entity("Emulsion.Database.Entities.TelegramContent", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<Int64>("ChatId")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("ChatUserName")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("FileId")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("FileName")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore
            b.Property<Int64>("MessageId")
                .IsRequired(true)
                .HasColumnType("INTEGER") |> ignore
            b.Property<string>("MimeType")
                .IsRequired(false)
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("TelegramContents") |> ignore

        )) |> ignore

